---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cert-manager-webhook-selectel.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ include "cert-manager-webhook-selectel.name" . }}
    chart: {{ include "cert-manager-webhook-selectel.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: {{ include "cert-manager-webhook-selectel.name" . }}
    release: {{ .Release.Name }}
