name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'charts/**'

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0
        with:
          version: v3.4.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct.yaml

  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
    strategy:
      matrix:
        k8s:
          - v1.17.14
          - v1.19.4
          - v1.21.6
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh

  # install-chart:
  #   name: install-chart
  #   runs-on: ubuntu-latest
  #   needs:
  #     - lint-chart
  #     - kubeval-chart
  #   strategy:
  #     matrix:
  #       k8s:
  #         - v1.17.14
  #         - v1.19.4
  #         - v1.21.6
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: Create kind ${{ matrix.k8s }} cluster
  #       uses: helm/kind-action@main
  #       with:
  #         node_image: kindest/node:${{ matrix.k8s }}
  #     - name: Run chart-testing (install)
  #       uses: helm/chart-testing-action@main
  #       with:
  #         command: install
  #         config: .github/ct.yaml
